
def questions():
    x = [ 'Which company was established on April 1st, 1976 by Steve Jobs, Steve Wozniak and Ronald Wayne?',
  'In any programming language, what is the most common way to iterate through an array?',
  'What does CPU stand for?',
  'Whistler was the codename of this Microsoft Operating System.',
  'What does AD stand for in relation to Windows Operating Systems? ',
  'HTML is what type of language?',
  'What five letter word is the motto of the IBM Computer company?',
  'On which computer hardware device is the BIOS chip located?',
  'In the programming language Java, which of these keywords would you put on a variable to make sure it doesn&#039;t get modified?',
  'Which of the following languages is used as a scripting language in the Unity 3D game engine?',
  'If you were to code software in this language you&#039;d only be able to type 0&#039;s and 1&#039;s.',
  'The series of the Intel HD graphics generation succeeding that of the 5000 and 6000 series (Broadwell) is called:',
  'Nvidia&#039;s headquarters are based in which Silicon Valley city?',
  'What did the name of the Tor Anonymity Network orignially stand for?',
  'What was the first commerically available computer processor?',
  'What was the name given to Android 4.3?',
  'Which of these is the name for the failed key escrow device introduced by the National Security Agency in 1993?',
  'The internet domain .fm is the country-code top-level domain for which Pacific Ocean island nation?',
  'While Apple was formed in California, in which western state was Microsoft founded?',
  'On Twitter, what was the original character limit for a Tweet?',
  'In the programming language &quot;Python&quot;, which of these statements would display the string &quot;Hello World&quot; correctly?',
  'In HTML, which non-standard tag used to be be used to make elements scroll across the viewport?',
  'In CSS, which of these values CANNOT be used with the &quot;position&quot; property?',
  'How fast is USB 3.1 Gen 2 theoretically?',
  'Which operating system was released first?',
  '.rs is the top-level domain for what country?',
  'Which data structure does FILO apply to?',
  'Which of the following is the oldest of these computers by release date?',
  'What does the term GPU stand for?',
  'America Online (AOL) started out as which of these online service providers?',
  'What does the International System of Quantities refer 1024 bytes as?',
  'What was the first Android version specifically optimized for tablets?',
  'Which of these people was NOT a founder of Apple Inc?',
  'Laserjet and inkjet printers are both examples of what type of printer?',
  'How many values can a single byte represent?',
  'What does the term MIME stand for, in regards to computing?',
  'The C programming language was created by this American computer scientist. ',
  'Which programming language was developed by Sun Microsystems in 1995?',
  'What vulnerability ranked #1 on the OWASP Top 10 in 2013?',
  'Who invented the &quot;Spanning Tree Protocol&quot;?',
  'Approximately how many Apple I personal computers were created?',
  'In programming, what do you call functions with the same name but different implementations?',
  'In computing, what does MIDI stand for?',
  'The acronym &quot;RIP&quot; stands for which of these?',
  'The teapot often seen in many 3D modeling applications is called what?',
  'Unix Time is defined as the number of seconds that have elapsed since when?',
  'How many bits make up the significand portion of a single precision floating point number?',
  'Which of the following computer components can be built using only NAND gates?',
  'What language does Node.js use?',
  'Which of these Cherry MX mechanical keyboard switches is both tactile and clicky?' ]
    return x

def answers():
    y = [ 'Apple',
    '&#039;For&#039; loops',
    'Central Processing Unit',
    'Windows XP',
    'Active Directory',
    'Markup Language',
    'Think',
    'Motherboard',
    'Final',
    'C#',
    'Binary',
    'HD Graphics 500',
    'Santa Clara',
    'The Onion Router',
    'Intel 4004',
    'Jelly Bean',
    'Clipper Chip',
    'Micronesia',
    'New Mexico',
    '140',
    'print(&quot;Hello World&quot;)',
    '&lt;marquee&gt;&lt;/marquee&gt;',
    'center',
    '10 Gb/s',
    'Mac OS',
    'Serbia',
    'Stack',
    'TRS-80',
    'Graphics Processing Unit',
    'Quantum Link',
    'Kibibyte',
    'Honeycomb',
    'Jonathan Ive',
    'Non-impact printer',
    '256',
    'Multipurpose Internet Mail Extensions',
    'Dennis Ritchie',
    'Java',
    'Injection ',
    'Radia Perlman',
    '200',
    'Overloading',
    'Musical Instrument Digital Interface',
    'Routing Information Protocol',
    'Utah Teapot',
    'Midnight, January 1, 1970',
    '23',
    'ALU',
    'JavaScript',
    'Cherry MX Blue' ]
    return y
