"""empty message

Revision ID: c7ceebaad73f
Revises: 54e7ec172145
Create Date: 2021-06-03 11:55:49.031203

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c7ceebaad73f'
down_revision = '54e7ec172145'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('friends', sa.Column('friendId', sa.Integer(), nullable=True))
    op.alter_column('friends', 'userId',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_foreign_key(None, 'friends', 'users', ['friendId'], ['id'])
    op.drop_column('friends', 'id')
    op.drop_column('friends', 'username')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('friends', sa.Column('username', sa.TEXT(), autoincrement=False, nullable=False))
    op.add_column('friends', sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.drop_constraint(None, 'friends', type_='foreignkey')
    op.alter_column('friends', 'userId',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('friends', 'friendId')
    # ### end Alembic commands ###
